[package]
name = "generator"
version = "0.1.0"
authors = ["Petr Hodina <hodinapetr46@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[build-dependencies]
moz-cheddar = "0.4.0"

[dependencies]
tera = "0.10.10" 
libc = "*"